spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: update | create | create-drop | none | validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect